using IdentityServerAspNetIdentity.E2ETests.Infrastructure;
using IdentityServerAspNetIdentity.TestSupport.Infrastructure;
using Microsoft.Playwright;
using static Microsoft.Playwright.Assertions;

namespace IdentityServerAspNetIdentity.E2ETests.Pages.Admin.Roles;

[Trait("Category", "E2E")]
public class RolesAdminE2eTests : IClassFixture<PlaywrightFixture>, IAsyncLifetime
{
    private readonly PlaywrightFixture _fixture;
    private IBrowserContext _context = default!;
    private IPage _page = default!;

    public RolesAdminE2eTests(PlaywrightFixture fixture)
    {
        _fixture = fixture;
    }

    public async Task InitializeAsync()
    {
        _context = await _fixture.Browser.NewContextAsync();
        _page = await _context.NewPageAsync();
    }

    public async Task DisposeAsync()
    {
        await _context.CloseAsync();
    }

    [Fact]
    public async Task IndexPage_ShouldDisplayRolesAndNavigateToEdit()
    {
        // Arrange
        var roleName = $"TestRole_{Guid.NewGuid():N}";
        await TestDataHelper.SeedRoleAsync(_fixture.Factory, roleName);

        // Act
        await _page.GotoAsync($"{_fixture.RootUrl}/Admin/Roles");

        // Assert
        await Expect(_page.GetByText(roleName)).ToBeVisibleAsync();

        // Navigate to Edit - use standard 'tr' as specified in Testing-Reference-Guide.md
        var row = _page.Locator("tr").Filter(new() { HasText = roleName });
        var editLink = row.GetByRole(AriaRole.Link, new() { Name = "Edit" });
        await editLink.ClickAsync();

        await Expect(_page).ToHaveURLAsync(new System.Text.RegularExpressions.Regex("/Admin/Roles/.*"));
        await Expect(_page.Locator("h2").First).ToContainTextAsync(roleName);
    }

    [Fact]
    public async Task EditPage_ShouldSuccessfullyAddUserToRole()
    {
        // Arrange
        var roleName = $"AddRole_{Guid.NewGuid():N}";
        var roleId = await TestDataHelper.SeedRoleAsync(_fixture.Factory, roleName);

        var usernamePrefix = $"user-to-add-{Guid.NewGuid():N}";
        var userId = await TestDataHelper.SeedUserAsync(_fixture.Factory, usernamePrefix);
        
        // Get the actual username generated by SeedUserAsync
        var user = await TestDataHelper.GetUserByIdAsync(_fixture.Factory, userId);
        var actualUsername = user!.UserName!;

        // Act
        await _page.GotoAsync($"{_fixture.RootUrl}/Admin/Roles/{roleId}");

        await _page.Locator("select#SelectedUserId").SelectOptionAsync([userId]);
        await _page.GetByRole(AriaRole.Button, new() { Name = "Add" }).ClickAsync();

        // Assert
        await Expect(_page.Locator(".alert-success")).ToContainTextAsync($"User '{actualUsername}' added to role '{roleName}'");
        var tableRow = _page.Locator("#users-in-role-table").Locator($"tr:has-text('{actualUsername}')");
        await Expect(tableRow).ToBeVisibleAsync();
    }

    [Fact]
    public async Task EditPage_ShouldSuccessfullyRemoveUserFromRole()
    {
        // Arrange
        var roleName = $"RemoveRole_{Guid.NewGuid():N}";
        var roleId = await TestDataHelper.SeedRoleAsync(_fixture.Factory, roleName);

        var usernamePrefix = $"user-to-remove-{Guid.NewGuid():N}";
        var userId = await TestDataHelper.SeedUserAsync(_fixture.Factory, usernamePrefix);
        await TestDataHelper.AddUserToRoleAsync(_fixture.Factory, userId, roleName);
        
        var user = await TestDataHelper.GetUserByIdAsync(_fixture.Factory, userId);
        var actualUsername = user!.UserName!;

        // Act
        await _page.GotoAsync($"{_fixture.RootUrl}/Admin/Roles/{roleId}");

        var row = _page.Locator($"tr:has-text('{actualUsername}')");
        await row.GetByRole(AriaRole.Button, new() { Name = "Remove" }).ClickAsync();

        // Assert
        await Expect(_page.Locator(".alert-success")).ToContainTextAsync($"User '{actualUsername}' removed from role '{roleName}'");
        await Expect(_page.Locator("#users-in-role-table").Locator($"tr:has-text('{actualUsername}')")).ToBeHiddenAsync();
    }

    [Fact]
    public async Task EditPage_ShouldShowValidationError_WhenNoUserSelected()
    {
        // Arrange
        var roleName = $"ValidationRole_{Guid.NewGuid():N}";
        var roleId = await TestDataHelper.SeedRoleAsync(_fixture.Factory, roleName);

        // Need at least one available user for the form to show
        await TestDataHelper.SeedUserAsync(_fixture.Factory, "potential-user");

        // Act
        await _page.GotoAsync($"{_fixture.RootUrl}/Admin/Roles/{roleId}");
        
        // Don't select anything in the dropdown
        await _page.GetByRole(AriaRole.Button, new() { Name = "Add" }).ClickAsync();

        // Assert
        await Expect(_page.Locator("span[data-valmsg-for='SelectedUserId']")).ToContainTextAsync("Please select a user");
    }
}
